name: Master- LiteManager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Downloading and Installing Essentials
        run: |
          Invoke-WebRequest -Url "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -Outfile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Connect to LiteManager
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
